#!/bin/sh
set -e

# FILENAME="nem-toolchain_$(uname -s)_$(uname -m).tar.gz"
FILENAME="nem-toolchain_Linux_x86_64.tar.gz"
RELEASES_URL="https://github.com/nem-toolchain/nem-toolchain/releases"

last_version() {
  curl -sL -o /dev/null -w %{url_effective} "$RELEASES_URL/latest" |
    rev | cut -f1 -d'/'| rev
}

test -z "$VERSION" && VERSION="$(last_version)"
test -z "$VERSION" && {
  echo "Unable to get nem-toolchain version." >&2
  exit 1
}

test -z "$TMPDIR" && TMPDIR="$(mktemp -d)"
curl -sL -o "$TMPDIR/$FILENAME" "$RELEASES_URL/download/$VERSION/$FILENAME"

mkdir -p bin
tar -xf "$TMPDIR/$FILENAME" -C bin nem
