#!/bin/sh
set -e

TAR_FILE="/tmp/nem.tar.gz"
RELEASES_URL="https://github.com/nem-toolchain/nem-toolchain/releases"

last_version() {
  curl -sL -o /dev/null -w %{url_effective} "$RELEASES_URL/latest" |
    rev |
    cut -f1 -d'/'|
    rev
}

test -z "$VERSION" && VERSION="$(last_version)"
test -z "$VERSION" && {
  echo "Unable to get nem-toolchain version." >&2
  exit 1
}

test -z "$TMPDIR" && TMPDIR="$(mktemp -d)"
rm -f "$TAR_FILE"
curl -s -L -o "$TAR_FILE" \
  "$RELEASES_URL/download/$VERSION/nem-toolchain_$(uname -s)_$(uname -m).tar.gz"

tar -xf "$TAR_FILE" -C "$TMPDIR"
export PATH="$PATH:$TMPDIR"
